$1 + 1$
$\alpha 와  \beta의 값이 같다$

$$\alpha = \beta $$

$\alpha$
$\beta$
$\gamma$
$$\delta$$
$$\zeta$$
$\epsilon$



In [8]:
from sklearn.datasets import load_iris
iris = load_iris()
data = iris.data[0 , :]

In [26]:
x2 = np.array([data])
x2

array([[5.1, 3.5, 1.4, 0.2]])

In [40]:
from sklearn.datasets import load_digits

digits = load_digits()
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [45]:
samples = [0, 10, 20, 30, 1, 11, 21, 31]  # 선택된 이미지 번호 

d = []
for i in range(8):
    d.append(digits.images[samples[i]]) 
    
plt.figure(figsize=(8, 2))
for i in range(8):
    plt.subplot(1, 8, i + 1)
    plt.imshow(d[i], interpolation='nearest', cmap=plt.cm.bone_r)
    plt.grid(False); plt.xticks([]); plt.yticks([])
    plt.title("image {}".format(i + 1))
plt.suptitle("숫자 0과 1 이미지")
plt.tight_layout()
plt.show()


In [48]:
v = []
for i in range(8):
    v.append(d[i].reshape(64, 1))  # 벡터화 plt.figure(figsize=(8, 3))
    
for i in range(8):
    plt.subplot(1, 8, i + 1)
    plt.imshow(v[i], aspect=0.4,
                    interpolation='nearest', cmap=plt.cm.bone_r)
    plt.grid(False); plt.xticks([]); plt.yticks([]) 
    plt.title("벡터 {}".format(i + 1))
plt.suptitle("벡터화된 이미지", y=1.05)
plt.tight_layout(w_pad=7)
plt.show()

In [49]:
from scipy import misc
img_rgb = misc.face()
img_rgb.shape

(768, 1024, 3)

In [52]:
x = np.array([[1,2,3]])

x

array([[1, 2, 3]])

In [53]:
x.T

array([[1],
       [2],
       [3]])

In [54]:
x.T.T

array([[1, 2, 3]])

In [57]:
x = np.diag([1, 2, 3])
x

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [60]:
#x = np.diag([1, 1, 1])
x = np.identity(3)
x


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
S = np.array([[1, 2], [2, 3]])
S

array([[1, 2],
       [2, 3]])

In [65]:
S.T

array([[1, 2],
       [2, 3]])

In [70]:
x = np.array([10, 11, 12])
y = np.array([0, 1, 2])
x, y

(array([10, 11, 12]), array([0, 1, 2]))

In [71]:
x + y

array([10, 12, 14])

In [72]:
a1 = np.array([[1],[2],[3]])
b1 = np.array([[3],[4],[5]])

In [80]:
an1 = a1.T @ b1
an1

array([[26]])

In [3]:
price =np.array([[100], [80], [50]])
count =np.array([[3], [4], [5]])
                

In [4]:
(price.T @ count)[0][0]

870

In [5]:
price.mean()

76.66666666666667

In [6]:
price - price.mean()

array([[ 23.33333333],
       [  3.33333333],
       [-26.66666667]])

In [ ]:
###유사도는 내적의 합...으로 표현 가능 - 백터의 유사도

In [8]:
from sklearn.datasets import load_digits

In [12]:
x = load_digits()
x

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [16]:
x = x.data

In [21]:
x[0, :] @ x[0, :]

3070.0

In [2]:
A  = np.array([[1, 2, 3],[4, 5, 6]])
B  = np.array([[2, 3],[4, 5], [6, 7]])


In [3]:
A @ B

array([[28, 34],
       [64, 79]])

In [4]:
B @ A

array([[14, 19, 24],
       [24, 33, 42],
       [34, 47, 60]])

In [5]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
a = np.array([1, 0, 7])
b = np.array([-2, 1, 0])

In [18]:
np.diag(a + b)

array([-1])

In [19]:
<a,b>

SyntaxError: invalid syntax (Temp/ipykernel_26144/2430209854.py, line 1)

In [31]:
np.linalg

<module 'numpy.linalg' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\linalg\\__init__.py'>

In [58]:
np.sqrt(np.linalg.norm(a)**2 + np.linalg.norm(b)**2 - (2 * np.linalg.norm(a.T * b)))

7.14142842854285

2.0