### 1. 선형회귀분석

- 프리미어리그 데이터(득점, 실점, 승점)
- 득점, 실점 -> 승점 예측하는 모델
- scikit-learn 패키지
    - 데이터 마이닝 및 데이터 분석, 모델을 위한 도구
    - 상업적으로 사용이 가능한 오픈소스

In [3]:
import numpy as np
import pandas as pd
import pickle
# 선형 회귀 모델
from sklearn import linear_model
# 학습 데이터와 테스트 데이터를 나눠주는 모듈
from sklearn.model_selection import train_test_split
# 모델을 평가해주는 모듈
from sklearn.metrics import mean_absolute_error

### 분석절차
- 데이터 로드
- 데이터 전처리 
    - 독립변수(샘플데이터)와 종속변수(결과데이터)를 나눔
    - 학습 데이터와 테스트 데이터를 나눔
    
- 데이터 분석 : 선형회귀 모델
- 성능평가 : MAE (Mean Absolute Evaluation)
- 예측 코드 작성

In [5]:
# 1. 데이터 로드
p_df = pd.read_csv("datas/premierleague.csv")

In [7]:
p_df

name   gf  ga  points
0            Manchester City  106  27     100
1          Manchester United   68  28      81
2          Tottenham Hotspur   74  36      77
3                  Liverpool   84  38      75
4                    Chelsea   62  38      70
5                    Arsenal   74  51      63
6                    Burnley   36  39      54
7                    Everton   44  58      49
8             Leicester City   56  60      47
9           Newcastle United   39  47      44
10            Crystal Palace   45  55      44
11               Bournemouth   45  61      44
12           West Ham United   48  68      42
13                   Watford   44  64      41
14  Brighton and Hove Albion   34  54      40
15         Huddersfield Town   28  58      37
16               Southampton   37  56      36
17              Swansea City   28  56      33
18                Stoke City   35  68      33
19      West Bromwich Albion   31  56      31

In [9]:
# 2. 데이터 전처리 
# 독립변수, 종속변수 나누기
df_x = p_df[["gf", "ga"]]
df_y = p_df[["points"]]


In [46]:
# 학습데이터, 테스트 데이터 나누기
train_x, test_x, train_y, test_y = train_test_split(df_x, df_y, test_size=0.3, random_state=1)

In [47]:
train_y



points
4       70
17      33
7       49
1       81
13      41
0      100
19      31
18      33
9       44
15      37
8       47
12      42
11      44
5       63

In [48]:
# 3. 데이터 분석 : 선형 회귀 모델
model = linear_model.LinearRegression()
model.fit(train_x, train_y)


LinearRegression()

In [49]:
# 4. 성능평가 : MAE
pred_y = model.predict(test_x)
pred_y


array([[80.88065736],
       [40.79778662],
       [50.9467527 ],
       [46.31419247],
       [76.04209484],
       [40.23228639]])

In [50]:
test_y["points"].values

array([75, 36, 54, 44, 77, 40], dtype=int64)

In [51]:
pred_y = np.around(pred_y.flatten()).astype(int)
pred_y

array([81, 41, 51, 46, 76, 40])

In [53]:
mae = mean_absolute_error(test_y, pred_y)
round(mae,2)

2.83

In [66]:
# 5. 예측함수 만들기
gf, ga = 80, 30
def make_df(gf, ga):
    return pd.DataFrame({"gf":[gf], "ga":[ga]})
result = int(model.predict(make_df(gf, ga)).flatten()[0])
result

83

In [68]:
# pickle 파일로 만들기
with open("datas/p_model.pkl","wb") as f:
    pickle.dump(model, f)

In [70]:
with open("datas/p_model.pkl","rb") as f:
    load_model = pickle.load(f)

In [71]:
gf, ga = 80, 30
def make_df(gf, ga):
    return pd.DataFrame({"gf":[gf], "ga":[ga]})
result = int(load_model.predict(make_df(gf, ga)).flatten()[0])
result

83

In [7]:
a = lambda c, d : pd.DataFrame({"a":c, "b":d})

In [8]:
a(3,5)

ValueError: If using all scalar values, you must pass an index

<function __main__.<lambda>(c, d)>

In [2]:
c = np.ndarray([[1, 0, 7]])
d = np.ndarray([[-2, 1, 0]])

TypeError: 'list' object cannot be interpreted as an integer